### ISSUE TITLE
Ebben a verzóban már megy az RTLMost Widevine plugin?

### ISSUE THREAD

**Issue by NH3CL** [vargalex/plugin.video.rtlmost#6]
Működik a lejátszás?

**Comment by vargalex** [comment]
Ez miért kérdés? Apróságok kerültek bele (műsor sorrendbe rendezés, jwt token cache-elése) a Movieshark repo-ban található verzióhoz képest, de abban is megy a lejátszás. A widevine-t nem az rtl most plugin biztosítja, az csak használja...
