### ISSUE TITLE
RTL+ subscription structure changed

### ISSUE THREAD

**Issue by kattantak** [vargalex/plugin.video.rtlmost#8]
After RTL modified subscription structure, addon not working for the premium content, 
even if RTL+ subscription is active and premium content working well in web browsers.

Could you you please update to be able to work again?

Thank you.

**Comment by penge1510** [comment]
Yes, I also confirm that this issue occured when I trying to play some content which needs premium subscription.

**Comment by vargalex** [comment]
I know, I working on it...

**Comment by penge1510** [comment]
> I know, I working on it...

Hi, 

Do you see any expected date about the fix? 

Thanks in advance!

**Comment by vargalex** [comment]
Sorry, but I haven't had time to look for a solution yet. So, I can't give you a deadline for the fix...

**Comment by adrianmihalko** [comment]
Ma teljesen leállt, semmit nem lehet megnyitni a kiegészítővel.

**Comment by vargalex** [comment]
Igen, tudok róla. Igyekszem mielőbb foglalkozni vele.

**Comment by vargalex** [comment]
The 2.2.32~alpha version works (released on Jan 12, 2023). The only problem is, that the RTL+ contents are red marked, even if you have RTL+ subscription. So, in the settings, you must turn off the "Előfizetetlen RTL Most+ tartalmak elrejtése" option.

**Comment by kanyos** [comment]
@vargalex az elérhető "fehér tartalmak" esetén, amiket korábban gond nélkül lejátszott a plugin, most "A hozzáféréshez RTL MOST+ előfizetés szükséges" üzenetet dob, és nem indul el a lejátszás. Mi lehet a gond? Köszi!

**Comment by vargalex** [comment]
@kanyos Kérnék további adatokat: milyen előfizetés, pontosan melyik anyag? Illetve böngészőben ugyan azzal a loginnal lejátszható-e?

**Comment by kanyos** [comment]
Sima regisztráció: RTL+ Light

Böngészőből ugyanazzal az accountal bármilyen ingyenesen elérhető tartalom lejátszató, példaképp:
https://www.rtlmost.hu/valovilag-p_7684/valovilag11-57-resz-c_12991072

KODI Log:
ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.rtlmost/?action=play&url=clip_12991072&meta=...

**Comment by vargalex** [comment]
Na, pont RTL+ Light-al nem teszteltem. Lehet, hogy nincs is olyanom, de legfeljebb regisztrálok egyet.

**Comment by vargalex** [comment]
@kanyos Megnéztem. Nekem az 51-57 részeket mutatja fehéren és simán le is játssza RTL+ Light accounttal. Az 51-nél régebbieket pirosan jelzi és nem is játssza le. Próbálj meg esetleg egy kijelentkezést, majd bejelentkezést.

**Comment by kanyos** [comment]
Valóban, pedig direkt újra raktam a plugint előtte default beállításokkal, de most az ismételt újra telepítés megoldotta! Elnézést érte és köszi!

**Comment by ynvaser** [comment]
Hali, ugyan ezzel az issue-val küzdök mint @kanyos. Nekem az újratelepítések meg a ki/be logolás sem oldotta meg a dolgot.

**Comment by kanyos** [comment]
@ynvaser nem tudom, hogy segíthet-e, illetve nem jöttem rá az összefüggésre, de volt olyan, hogy böngészőből is elhalt néha a lejátszás / megjelenítés, cross origin dolgokra hivatkozva. Nekem másik IP címről történő megnyitás, pl. mobil netre átcsatlakozás megoldotta magában a pluginben is a dolgot, majd a sikeres egyszeri lejátszás után már az eredeti hálózaton is ment minden. Elég hektikus és megmagyarázhatatlan, dehát "számítástechnika" :)

**Comment by vargalex** [comment]
A CORS origin böngésző oldali ellenőrzés, nem szerver oldali és az addon sem foglalkozik vele. Az IP címhez nem szabadna, hogy köze legyen egyszerűen azt mondja, hogy melyik URL-ről melyik másik host-ot szólíthatja meg a böngésző.

**Comment by kattantak** [comment]
Hello, Nalam volt kicsi szorakozas widevine-al, de most mar mukodik jol. Koszi szepen @vargalex
